# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ParticleExample' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  flags = get_default_flags()

  pod 'ConnectWalletConnectAdapter'
  pod 'ConnectPhantomAdapter'
  pod 'ConnectEVMAdapter'
  pod 'ConnectSolanaAdapter'
  pod 'ParticleConnect'
  pod 'ConnectCommon'

  pod 'ParticleNetworkBase'
  pod 'ParticleNetworkChains'

  pod 'AuthCoreAdapter', :modular_headers => false
  pod 'ParticleAuthCore', :modular_headers => false
  pod 'ParticleMPCCore'
  pod 'Thresh'
  
  pod 'ParticleConnectKit'

  pod 'AWSCore', :modular_headers => false

  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'
  pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'

  use_react_native!(
    :path => config[:reactNativePath],

    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          if target.name == 'SDWebImage' || target.name == 'SDWebImageSwiftUI'
            config.build_settings['DEFINES_MODULE'] = 'YES'
          end
        end
      end
  end
end
